<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerZsxc5zz\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerZsxc5zz/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerZsxc5zz.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerZsxc5zz\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerZsxc5zz\appProdProjectContainer([
    'container.build_hash' => 'Zsxc5zz',
    'container.build_id' => '7b86552d',
    'container.build_time' => 1601580180,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerZsxc5zz');
